scenario_name = "Sea of Isolation"
ship_name = "Nomad Bootstrap"
ship_acquired = "Temporary hull used while initializing the Nomad carrier."
ship_model = "Llama"
credits = 30000
system = "Delta Polaris"
system_position = [-12500, -3500]
event = "Nomad Start"
chapter = "0"
date = "UST 603:3726.2871"
gui_default = "slim"
spob_lua_default = "spob/lua/default.lua"
dtype_default = "energy"
local_map_default = "Local System Map"
